// import headImg from './images/navicon.png';


export default function Head() {
  return (
    <>
      <title>nutrition tracker</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/apple.png" />
    </>
  )
}
