import { MyProvider } from '@/MyContext';
import NavBar from './components/NavBar';
import './globals.css';
import './output.css';
import Providers from './Providers';
import { Oswald, Kanit } from '@next/font/google';
import { Metadata } from 'next';


export const metadata: Metadata = {
  title: 'nutrition tracker',
  description: 'track your nutrition progress daily',
  
};




// export default function Head() {
//   return (
//     <>
//       <title>nutrition tracker</title>
//       <meta content="width=device-width, initial-scale=1" name="viewport" />
//       <meta name="description" content="Generated by create next app" />
//       <link rel="icon" href="/apple.png" />
//     </>
//   )
// }








const oswald = Oswald({
  weight: ['400', '500'],
  subsets: ['latin'],
});
const kanit = Kanit({
  weight: ['400', '500'],
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head />

      <MyProvider>
        <body className={kanit.className}>
          <main className='w-screen'>
            <NavBar />
            <Providers>{children}</Providers>
          </main>
        </body>
      </MyProvider>
    </html>
  );
}
